#! /bin/sh
#
# Check whether tmp1 and tmp2 indices are same.
#
# tmp1: simply indexed.
# tmp2: incrementally indexed.
#

cd tmp1
targets=`find . -type f -name 'NMZ.*' | \
              egrep -v "NMZ\.(log|r|slog|status)$"`  # Exclude them.
cd ..

for target in $targets; do
    diff "tmp1/$target" "tmp2/$target"
    test "$?" != "0" && exit 1  # error if not success
done
exit 0
