#! /bin/sh
#
# Check whether idx1 and idx2 indices are same.
#
# idx1: simply indexed.
# idx2: incrementally indexed.
#

cd idx1
targets=`find . -type f -name 'NMZ.*' | \
              egrep -v "NMZ\.(log|r|slog|status|err)$"`  # Exclude them.
cd ..

for target in $targets; do
    diff "idx1/$target" "idx2/$target"
    test "$?" != "0" && exit 1  # error if not success
done
exit 0
