#! /bin/sh
#
# Test for japanese filename.
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG

EXEC=no

lc_all=$LC_ALL
lc_ctype=$LC_CTYPE
lang=$LANG

for ctype in "$lc_all" "$lc_ctype" "$lang"; do
    if test -n "$ctype" -a "$ctype" = "C"; then
        ctype="en"
        break
    fi
    cand=`echo "$ctype" | LC_ALL="C" perl -nle 'print $1 if /^(..)/'`
    if test -n "$cand"; then
        ctype=$cand
        break
    fi
done

case $ctype in 
        ja*)
                EXEC=yes
                ;;
esac
if [ $EXEC = 'no' ]
then
        echo "Skipping because of LANG does not begin with ja: $0" >> $LOG
        exit 77
fi


perl <<'TEST'
    my $LOG = "test-log";
    my %files = ('EUC-JP'    => "%A4%CA%A4%DE%A4%BA.html",
		'Shift_JIS' => "%82%C8%82%DC%82%B8.html",
		'UTF-8'     => "%E3%81%AA%E3%81%BE%E3%81%9A.html",
		'CAP' => ":82:C8:82:DC:82:B8.html");
    my $exitresult = 0;
    for $dir (keys(%files)) {

	my $idxdir = "ja-idx4/$dir";
        my $rcfile = "namazurc-ja4";

	open FH1, ">$rcfile";
	my $coding = $dir;
	if ($coding =~ /CAP/) {
	    $coding = "CP932#" . $coding;
	}
	print FH1  "Filesys_coding $coding\n";
	close FH1;
	open FH2, "../src/namazu namazu -l -f namazurc-ja4 $idxdir |";
	while (defined(my $result = <FH2>)){
	    unless ($result =~ /$files{$dir}/i){
		$exitresult = 1;
	    }
	}
	close FH2;
	unlink $rcfile;
    }
    exit $exitresult;
TEST
exit $?
