#! /bin/sh
#
# Test for duplicated field.
#
LOG=`pwd`/test-log
TARGET=$srcdir/data/dup-field
IDX=idx18
CONF=`pwd`/tmp.mknmzrc
echo '  *** starting ' $0 >>$LOG

if test ! -d $IDX; then
    mkdir $IDX
else
    rm -f $IDX/NMZ.*
fi

echo 'package conf;' > $CONF
echo '$SEARCH_FIELD = "keywords|message-id|subject|from|date|uri|newsgroups|to|summary|size";' >> $CONF
echo '$META_TAGS = "keywords|description";' >> $CONF

../scripts/mknmz --meta -f $CONF -O $IDX $TARGET >> $LOG 2>&1

COUNT=`egrep 'test' $IDX/NMZ.field.keywords|wc -l`

if [ $COUNT -ne 1 ]
then
	exit 1
fi

exit 0
