#! /bin/sh
#
# Test for $FILTERDIR, File::MMagic and decide_type()
#

LOG=`pwd`/test-log
TARGET=$top_srcdir/tests/data/filter/  # from script
echo '  *** starting ' $0 >>$LOG

IDXDIR=idx15
TXTCOUNT=`ls $TARGET/*.txt $TARGET/*.x-test |wc -l`
FDIR=$top_srcdir/tests/data/filter
pwd=`pwd`
tmprc="$pwd/tmp.mknmzrc-mknmz12"

if test ! -d $IDXDIR; then
    mkdir $IDXDIR
else
    rm -f $IDXDIR/NMZ.*
fi

echo "package conf; \$FILTERDIR='$FDIR';" > $tmprc
RESULTCOUNT=`../scripts/mknmz -f $tmprc -C|egrep x-test|wc -l`
rm -f $tmprc
test $RESULTCOUNT -eq 1 || exit $?

echo "package conf; \$FILTERDIR='$FDIR';" > $tmprc
if  test ! -d $IDXDIR; then 
    mkdir     $IDXDIR
fi

../scripts/mknmz -f $tmprc --allow='.*\.(txt|x-test\d*)' -O $IDXDIR $TARGET >> $LOG 2>&1
rm -f $tmprc

COUNT=`egrep 'x-test-author' $IDXDIR/NMZ.field.from|wc -l`
if [ $COUNT -ne $TXTCOUNT ]
then
    exit 1
fi

RESULTCOUNT=`wc -l < $IDXDIR/NMZ.field.uri`
if [ $TXTCOUNT -ne $RESULTCOUNT ]
then
    exit 1
fi

exit 0
