#! /bin/sh
#
# Test for simple indexing.
#
LOG=`pwd`/test-log

if test ! -d idx1; then
    mkdir idx1
else
    rm -f idx1/NMZ.*
fi

# Simple indexing.
cd ../scripts 
./mknmz -O ../tests/idx1 ../tests/data >> $LOG
exit $?
