#! /bin/sh
#
# Test for simple indexing.
#

if test ! -d idx1; then
    mkdir idx1
else
    rm -f idx1/NMZ.*
fi

# Simple indexing.
cd ../scripts 
./mknmz -O ../tests/idx1 ../tests/data >> ../tests/test-log
exit $?
