#! /bin/sh
#
# Test for symlink directory
#

LOG=`pwd`/test-log
TARGET=`pwd`/data/symlink
IDXDIR=idx14

if test ! -d $IDXDIR; then
    mkdir $IDXDIR
else
    rm -f $IDXDIR/NMZ.*
fi

if test ! -h $TARGET; then
    ln -s `pwd`/data/en $TARGET
fi
TXTCOUNT=`ls ./data/symlink/*.txt|wc -l`

cd ../scripts
./mknmz --allow='.*.txt' -O ../tests/$IDXDIR $TARGET >> $LOG 2>&1
RESULTCOUNT=`wc -l < ../tests/$IDXDIR/NMZ.field.uri`
test $TXTCOUNT -eq $RESULTCOUNT
exit $?