#! /bin/sh
#
# Test for incremental indexing.
#
LOG=`pwd`/test-log
TARGET=`./select-data`

if test ! -d idx2; then
    mkdir idx2
else
    rm -f idx2/NMZ.*
fi

cd ../scripts
targets=`cat ../tests/idx1/NMZ.field.uri`

for target in $targets; do
   ./mknmz --no-delete -O ../tests/idx2 $target \
	>> $LOG
    test "$?" != "0" && exit 1  # error if not success
done;

exit 0;
