#! /bin/sh
#
# Test for deleting documents in an index.
#
LOG=`pwd`/test-log
TARGET=`./select-data`

if test ! -d idx4; then
    mkdir idx4
else
    rm -f idx4/NMZ.*
fi

TMPDATA=`pwd`/tmp-data
# Copy docments.
if test -d tmp-data; then
    rm -rf tmp-data
fi
cp -rp $TARGET tmp-data

# Simple indexing.
cd ../scripts 
./mknmz -O ../tests/idx4 $TMPDATA >> $LOG
test "$?" != "0" && exit 1  # error if not success

prevdocnum=`perl -lne 'print $1 if /^files (\d+)/' ../tests/idx4/NMZ.status`

# Remove some documents.
cd $TMPDATA
find . -type f -name '*.txt' | xargs rm -f
cd ../

# Update the index.
cd ../scripts 
./mknmz --update=../tests/idx4 >> $LOG
test "$?" != "0" && exit 1  # error if not success

postdocnum=`perl -lne 'print $1 if /^files (\d+)/' ../tests/idx4/NMZ.status`

echo "predocnum:" $prevdocnum, "postdocnum:" $postdocnum >> $LOG
test $prevdocnum -le $postdocnum && exit 1  # error if prev <= post
exit 0
