#! /bin/sh
#
# Test for incremental indexing.
#
if test ! -d tmp2; then
    mkdir tmp2
else
    rm -f tmp2/NMZ.*
fi

cd ../tests/data
pwd=`pwd`
targets=`find $pwd -type f | grep -v CVS | grep -v Makefile | sort`
cd ../../scripts
for target in $targets; do
   ./mknmz --no-delete -O ../tests/tmp2 $target \
	>>../tests/test-log
    test "$?" != "0" && exit 1  # error if not success
done;

exit 0;
