#! /bin/sh
#
# Test for incremental indexing.
#
LOG=`pwd`/test-log
if test ! -d idx2; then
    mkdir idx2
else
    rm -f idx2/NMZ.*
fi

cd ../tests/data
pwd=`pwd`
targets=`find $pwd -type f | grep -v CVS | grep -v Makefile | sort`
cd ../../scripts
for target in $targets; do
   ./mknmz --no-delete -O ../tests/idx2 $target \
	>> $LOG
    test "$?" != "0" && exit 1  # error if not success
done;

exit 0;
