#! /bin/sh
#
# Test for indexing with --checkpoint and $ON_MEMORY_MAX is 0.
#
LOG=`pwd`/test-log
TARGET=`./select-data`

if test ! -d idx3; then
    mkdir idx3
else
    rm -f idx3/NMZ.*
fi

pwd=`pwd`
tmprc="$pwd/mknmzrc"
echo '$conf::ON_MEMORY_MAX=0' > $tmprc

# Simple indexing
cd ../scripts 
./mknmz --checkpoint -f $tmprc -O ../tests/idx3 $TARGET >> $LOG
rm -f $tmprc

exit $?
