#! /bin/sh
#
# Test for namazu.cgi with "ContentType" directive.
#
LOG=`pwd`/test-log
echo '  *** starting ' $0 >>$LOG
pwd=`pwd`

tmprc=".namazurc"
echo "Index $pwd" > $tmprc
echo 'ContentType "text/x-hdml"' >> $tmprc

# To make messages English
LANG= ; export LANG
unset LANGUAGE
unset LC_ALL
unset LC_MESSAGES

SCRIPT_NAME='namazu.cgi'
QUERY_STRING='query=namazu&idxname=idx1&lang=C'
export SCRIPT_NAME QUERY_STRING 

../src/namazu.cgi | \
grep "text/x-hdml" > /dev/null || exit 1

rm -f $tmprc

exit 0
