#! /bin/sh
#
# Test for namazu.cgi. Two indices are searched at once.
#

docnum=`perl -lne 'print $1 if /^files (\d+)/' "idx1/NMZ.status"`
docnum=`expr $docnum + $docnum`

pwd=`pwd`

tmprc="../src/.namazurc"
echo "Index $pwd" > $tmprc
echo "Template $pwd/idx1" >> $tmprc

SCRIPT_NAME='namazu.cgi'
QUERY_STRING='query=namazu&idxname=idx1&idxname=idx2'
export SCRIPT_NAME QUERY_STRING

cd ../src
hitnum=`./namazu.cgi | perl -ne 'print $1 if /<!-- HIT -->(\d+)<!-- HIT -->/'`
rm -f $tmprc

#echo $docnum $hitnum
test "$docnum" != "$hitnum" && exit 1  # error if not matched
exit 0
