#! /bin/sh
#
# Test for namazu.cgi.
#

docnum=`perl -lne 'print $1 if /^files (\d+)/' "tmp1/NMZ.status"`

pwd=`pwd`
tmprc="../src/.namazurc"
echo "Index $pwd" > $tmprc

SCRIPT_NAME='namazu.cgi'
QUERY_STRING='query=namazu&idxname=tmp1'
export SCRIPT_NAME QUERY_STRING

cd ../src
hitnum=`./namazu.cgi | perl -ne 'print $1 if /<!-- HIT -->(\d+)<!-- HIT -->/'`
rm -f $tmprc

#echo $docnum $hitnum
test "$docnum" != "$hitnum" && exit 1  # error if not matched
exit 0
