#! /bin/sh
#
# Test for index version check.
#
LOG=`pwd`/test-log
IDX=`pwd`/idx8
echo '  *** starting ' $0 >>$LOG

MSG="Present index is old type. it's unsupported."

# To make messages English
LANG= ; export LANG
unset LANGUAGE
unset LC_ALL
unset LC_MESSAGES
unset LC_CTYPE

mv $IDX/NMZ.wi $IDX/NMZ.wi.org

../src/namazu 'namazu' $IDX | grep "$MSG" > /dev/null || exit 1

mv $IDX/NMZ.wi.org $IDX/NMZ.wi

exit 0
