#! /bin/sh
#
# Test for emphasised keyword
#
LOG=`pwd`/test-log
IDX=`pwd`/idx17
echo '  *** starting ' $0 >>$LOG

# To make messages English
LANG= ; export LANG
unset LANGUAGE
unset LC_ALL
unset LC_MESSAGES
unset LC_CTYPE

../src/namazu -h 'emphasise' $IDX | grep "emphasised" > /dev/null || exit 1
