#!/bin/sh
# Created by Akira Higuchi (a-higuti@math.sci.hokudai.ac.jp)
# Modified by Ryuji Abe <raeva@t3.rim.or.jp>

cat > tmp.c << EOM
#include <stdio.h>
int main()
{
	int c;
	while ((c = getchar()) != EOF) {
		if ((c >= 0x81 && c <= 0x9f) ||
		    (c >= 0xe0 && c <= 0xfa)) {
			int x;
			printf("\\\\%3o", c);
			if ((x = getchar()) == EOF) return 1;
			printf("\\\\%3o", x);
		} else {
			putchar(c);
		}
	}
	return 0;
}
EOM
cc tmp.c -o tmp.aout &&
(
	nkf -s ja.po | ./tmp.aout | \
	sed -e "s/charset=EUC-JP/charset=Shift_JIS/g" > ja_JP.SJIS.po
	rm -f tmp.c tmp.aout
	test -s ja_JP.SJIS.po
)
