#ifndef _CGI_H
#define _CGI_H

struct cgivar {
    char *name;
    char *value;
    struct cgivar *next;
};
typedef struct cgivar CGIVAR;

/*
 * cgiarg: data structure for passing process_cgi_var_*() functions 
 * as a second arg as a pointer.
 */
struct cgiarg {
    char *query;
    char *subquery;
};


struct cgivar_func {
    char *name;
    void (*func)(char*, struct cgiarg*);
};

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Dec  9 09:37:44 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern void init_cgi ( char *query, char *subquery );

#else /* __STDC__ */

extern void init_cgi (/* char *query, char *subquery */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#endif /* _CGI_H */
