#ifndef _ALIAS_H
#define _ALIAS_H

#include "libnamazu.h" /* for enum nmz_stat */

struct nmz_alias {
    char *alias;
    char *real;
    struct nmz_alias *next;
};

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sat Dec  4 17:23:31 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern enum nmz_stat add_alias ( char *alias, char *real );
extern void free_aliases ( void );
extern struct nmz_alias *get_aliases ( void );
extern void show_aliases ( void );

#else /* __STDC__ */

extern enum nmz_stat add_alias (/* char *alias, char *real */);
extern void free_aliases (/* void */);
extern struct nmz_alias *get_aliases (/* void */);
extern void show_aliases (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */

#endif /* _ALIAS_H */
