#ifndef _FIELD_H
#define _FIELD_H

#define FIELD_SAFE_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

enum {
    FIELD_CACHE_SIZE = 8        /* Size of field caches */
};

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Dec  9 10:20:53 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern int isfield ( char *key );
extern void get_field_name ( char *field, char *str );
extern void get_field_data ( int idxid, int docid, char *orig_field, char *data );

#else /* __STDC__ */

extern int isfield (/* char *key */);
extern void get_field_name (/* char *field, char *str */);
extern void get_field_data (/* int idxid, int docid, char *orig_field, char *data */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#endif /* _FIELD_H */
