/*
 * 
 * mode.h - Namazu mode controlling class.
 *
 * $Id: mode.h,v 1.3 1999-11-23 09:46:18 satoru Exp $
 * 
 */

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Nov 23 16:33:11 1999
 */
extern void set_sortmethod ( int );
extern int get_sortmethod ( void );
extern void set_sortorder ( int );
extern int get_sortorder ( void );
extern void set_listwhence ( int );
extern int get_listwhence ( void );
extern void set_debugmode ( int );
extern int is_debugmode ( void );
extern void set_loggingmode ( int );
extern int is_loggingmode ( void );
extern void set_dyingmessage ( char * );
extern char *get_dyingmessage ( void );

