#ifndef _CONF_H
#define _CONF_H

#define DIRECTIVE_CHARS "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Dec  7 17:39:01 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern char *set_namazurc ( char *arg );
extern enum nmz_stat load_rcfile ( char *av0 );
extern void show_rcfile ( void );

#else /* __STDC__ */

extern char *set_namazurc (/* char *arg */);
extern enum nmz_stat load_rcfile (/* char *av0 */);
extern void show_rcfile (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#endif /* _CONF_H */
