#ifndef _REPLACE_H
#define _REPLACE_H

#include "libnamazu.h" /* for enum nmz_stat */

struct nmz_replace {
    char  *pat;  /* pattern */
    char  *rep;  /* replacement */
    struct re_pattern_buffer *pat_re; /* compiled regex of the pattern */
    struct nmz_replace *next;
};

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Sat Dec  4 18:22:43 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern void free_replaces ( void );
extern int replace_uri ( char *uri );
extern enum nmz_stat add_replace ( char *pat, char *rep );
extern void show_replaces ( void );

#else /* __STDC__ */

extern void free_replaces (/* void */);
extern int replace_uri (/* char *uri */);
extern enum nmz_stat add_replace (/* char *pat, char *rep */);
extern void show_replaces (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#endif /* _REPLACE_H */
