#ifndef _SEARCH_H
#define _SEARCH_H

#include "libnamazu.h" /* for NmzResult type */

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Dec  7 18:22:50 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern void free_hitnums ( struct nmz_hitnum *hn );
extern int binsearch ( char *orig_key, int prefix_match_mode );
extern NmzResult nmz_search ( char *query );
extern NmzResult do_search ( char *orig_key, NmzResult val );

#else /* __STDC__ */

extern void free_hitnums (/* struct nmz_hitnum *hn */);
extern int binsearch (/* char *orig_key, int prefix_match_mode */);
extern NmzResult nmz_search (/* char *query */);
extern NmzResult do_search (/* char *orig_key, NmzResult val */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#endif /* _SEARCH_H */
