/*

  util.h -

  $Author: satoru $
  $Date: 1999-12-09 03:15:15 $
  created at: Thu Mar  9 11:55:53 JST 1995

  Copyright (C) 1993-1998 Yukihiro Matsumoto

  Modifications for Namazu 
  by satoru-t@is.aist-nara.ac.jp

*/

#ifndef _UTIL_H
#define _UTIL_H

#include <stdio.h> /* for FILE struct */

#ifdef HAVE__VSNPRINTF
#define vsnprintf(str,n,format,ap) _vsnprintf(str,n,format,ap)
#endif /* HAVE__VSNPRINTF */

/*
 *
 * Macros
 *
 */

#define iskanji1st(c) (((uchar)(c) >= 0x81 && \
                       (uchar)(c)) <= 0x9f || \
                       ((uchar)(c) >= 0xe0 && \
                       (uchar)(c) <= 0xfc))
#define iskanji2nd(c) (((uchar)(c) >= 0x40 && \
                       (uchar)(c) <= 0xfc && \
                       (uchar)(c) != 0x7f))
#define iseuc(c)  ((uchar)(c) >= 0xa1 && (uchar)(c) <= 0xfe)
#ifndef iskanji /* for jperl */
#define iskanji(c)  (iseuc(*(c)) && iseuc(*(c + 1)))
#endif
#define ischoon(c) ((uchar)*(c) == 0xa1 && \
                    (uchar)*(c + 1) == 0xbc)
#define iseuc(c)  ((uchar)(c) >= 0xa1 && (uchar)(c) <= 0xfe)

/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Thu Dec  9 09:39:24 1999
 */
#ifndef __CEXTRACT__
#if __STDC__

extern unsigned long scan_oct ( char *start, int len, int *retlen );
extern unsigned long scan_hex ( char *start, int len, int *retlen );
extern void * xmalloc ( unsigned long size );
extern void * xrealloc ( void *ptr, unsigned long size );
extern void nmz_tr ( char *str, char *lstr, char *rstr );
extern void nmz_chomp ( char * s );
extern void strlower ( char *str );
extern char *lastc ( char *str );
extern size_t freadx ( void *ptr, size_t size, size_t nmemb, FILE *stream );
extern int nmz_get_unpackw ( FILE *fp, int *data );
extern int nmz_read_unpackw ( FILE *fp, int *buf, int size );
extern long getidxptr ( FILE * fp, long p );
extern int issymbol ( int c );
extern void nmz_die ( char *fmt, ... );
extern void nmz_die_with_msg ( void );
extern void nmz_wprintf ( char *fmt, ... );
extern void nmz_dprintf ( char *fmt, ... );
extern void nmz_pathcat ( char *base, char *name );
extern int isnumstr ( char *str );
extern void commas ( char *str );
extern char *strcasestr ( char *haystack, char *needle );
extern int strprefixcasecmp ( char *str1, char *str2 );
extern int strprefixcmp ( char *str1, char *str2 );
extern int strsuffixcmp ( char *str1, char *str2 );
extern char *nmz_readfile ( char *fname );
extern void nmz_subst ( char *p, char *pat, char *rep );
extern void nmz_cat ( char *fname );
extern char *safe_getenv ( char *s );
extern void print ( char *s );
extern void decode_uri ( char * s );

#else /* __STDC__ */

extern unsigned long scan_oct (/* char *start, int len, int *retlen */);
extern unsigned long scan_hex (/* char *start, int len, int *retlen */);
extern void * xmalloc (/* unsigned long size */);
extern void * xrealloc (/* void *ptr, unsigned long size */);
extern void nmz_tr (/* char *str, char *lstr, char *rstr */);
extern void nmz_chomp (/* char * s */);
extern void strlower (/* char *str */);
extern char *lastc (/* char *str */);
extern size_t freadx (/* void *ptr, size_t size, size_t nmemb, FILE *stream */);
extern int nmz_get_unpackw (/* FILE *fp, int *data */);
extern int nmz_read_unpackw (/* FILE *fp, int *buf, int size */);
extern long getidxptr (/* FILE * fp, long p */);
extern int issymbol (/* int c */);
extern void nmz_die (/* char *fmt, ... */);
extern void nmz_die_with_msg (/* void */);
extern void nmz_wprintf (/* char *fmt, ... */);
extern void nmz_dprintf (/* char *fmt, ... */);
extern void nmz_pathcat (/* char *base, char *name */);
extern int isnumstr (/* char *str */);
extern void commas (/* char *str */);
extern char *strcasestr (/* char *haystack, char *needle */);
extern int strprefixcasecmp (/* char *str1, char *str2 */);
extern int strprefixcmp (/* char *str1, char *str2 */);
extern int strsuffixcmp (/* char *str1, char *str2 */);
extern char *nmz_readfile (/* char *fname */);
extern void nmz_subst (/* char *p, char *pat, char *rep */);
extern void nmz_cat (/* char *fname */);
extern char *safe_getenv (/* char *s */);
extern void print (/* char *s */);
extern void decode_uri (/* char * s */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
#endif /* _UTIL_H */

